In [ ]:
#Importar dados essenciais
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

#Reading Dataset
from google.colab import drive
drive.mount('/content/drive/')


dataset = pd.read_csv('/content/drive/My Drive/CursoIA/ClassBartHomer/personagens.csv')
dataset

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


laranja_camisa_bart  azul_calcao_bart  azul_sapato_bart  \
0               6.886102          3.495204          1.484984   
1               5.004901          3.183889          1.000142   
2               5.264620          5.029683          0.283567   
3               0.000000          0.000000          0.000000   
4               8.978929          3.459119          0.000000   
..                   ...               ...               ...   
288             0.000000          0.000000          0.000000   
289             0.000000          0.000000          0.000000   
290             0.000000          0.000000          0.000000   
291             0.000000          0.000000          0.000000   
292             0.000000          0.000000          0.000000   

     marrom_boca_homer  azul_calca_homer  cinza_sapato_homer classe  
0             0.000000          0.000000            0.062954   Bart  
1             0.000000          0.000000            0.033024   Bart  
2             0.000000          0.000000            0.151573   Bart  
3             0.480168          0.000000            0.021164   Bart  
4             0.000000          0.000000            0.011593   Bart  
..                 ...               ...                 ...    ...  
288           0.000000          6.485412            0.093921  Homer  
289           0.000000          0.000000            0.042194  Homer  
290           0.000000          4.263629            0.076761  Homer  
291           0.000000          1.429134            0.017013  Homer  
292          13.744248          0.853902            0.063546  Homer  

[293 rows x 7 columns]

In [ ]:
#Splitting dataset
previsores = dataset.iloc[:, 0:6].values
print(previsores)
classes = dataset.iloc[:,6].values
print(classes)

[[ 6.886102    3.4952044   1.4849836   0.          0.          0.06295441]
 [ 5.004901    3.1838887   1.0001415   0.          0.          0.03302354]
 [ 5.2646203   5.0296826   0.283567    0.          0.          0.15157256]
 ...
 [ 0.          0.          0.          0.          4.2636285   0.07676148]
 [ 0.          0.          0.          0.          1.4291335   0.01701349]
 [ 0.          0.          0.         13.744248    0.853902    0.0635462 ]]
['Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart'
 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bart' 'Bar

In [ ]:
labelEncoder = LabelEncoder()
classes =  labelEncoder.fit_transform(classes)
print(classes)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classes, test_size=0.25)

In [ ]:
previsores_treinamento

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 8.4906764e-02,
        1.4057375e+00, 1.9634688e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        2.6704855e+00, 1.3297872e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 2.5594732e-02],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        3.1635802e-02, 4.6296297e-03],
       [6.8861020e+00, 3.4952044e+00, 1.4849836e+00, 0.0000000e+00,
        0.0000000e+00, 6.2954410e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.4950413e+01,
        1.3752067e+00, 1.5272727e+00]])

In [ ]:
classe_treinamento

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [ ]:
classificador = Sequential()
classificador.add(Dense(units =  6,
                        activation = 'relu',
                        input_dim = 6))
classificador.add(Dense(units =  4,
                        activation = 'relu'))
classificador.add(Dense(units =  1,
                        activation = 'sigmoid',
                        ))
classificador.compile(optimizer = 'adam',
                      loss = 'binary_crossentropy',
                      metrics = ['accuracy'])

In [ ]:
classificador.fit(previsores_treinamento,
                  classe_treinamento,
                  validation_data = (previsores_teste, classe_teste),
                  batch_size = 10,
                  epochs = 500)

Epoch 1/500
22/22 [==============================] - 1s 15ms/step - loss: 0.7759 - accuracy: 0.4612 - val_loss: 0.7783 - val_accuracy: 0.4730
Epoch 2/500
22/22 [==============================] - 0s 5ms/step - loss: 0.7140 - accuracy: 0.4475 - val_loss: 0.7065 - val_accuracy: 0.4324
Epoch 3/500
22/22 [==============================] - 0s 5ms/step - loss: 0.6646 - accuracy: 0.4658 - val_loss: 0.6635 - val_accuracy: 0.4595
Epoch 4/500
22/22 [==============================] - 0s 5ms/step - loss: 0.6318 - accuracy: 0.5662 - val_loss: 0.6279 - val_accuracy: 0.6892
Epoch 5/500
22/22 [==============================] - 0s 5ms/step - loss: 0.6041 - accuracy: 0.7945 - val_loss: 0.5952 - val_accuracy: 0.8514
Epoch 6/500
22/22 [==============================] - 0s 5ms/step - loss: 0.5766 - accuracy: 0.8265 - val_loss: 0.5654 - val_accuracy: 0.8919
Epoch 7/500
22/22 [==============================] - 0s 5ms/step - loss: 0.5490 - accuracy: 0.8402 - val_loss: 0.5311 - val_accuracy: 0.8919
Epoch 8/500
